FROM debian:wheezy

#Default branch name develop
ARG BRANCH_NAME=develop
#Default
ARG REPO_SLUG=steepcoin/steepcoin
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo

#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY steepcoin.tar.gz /steepcoin.tar.gz
RUN tar -xvf /steepcoin.tar.gz

#ADD . /steepcoin
RUN cd /steepcoin/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /steepcoin && scripts/windows-crosscompile/compile-steepcoin.sh
